
name: sample workflow
on:
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - run: |
          docker version
          pwd
          ls
      - name: build image
        run: docker build . --file Dockerfile --tag sampleimage:v1
